# Site settings
title: A blog about Guangyu(David) Xu
description: A blog about Guangyu(David) Xu
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Guangyu Xu
user_description: Five years of experience leading mobile and online game development teams through full game development life cycle. Includes designing systems to front-end development, UE/UX design, and 3D animation. I have great exposure to web technologies by creating 3 websites using HTML5, CSS3 and Javascript Frameworks and databases. I am strong with include Angular, React/Redux, Node.js/Express, MongoDB and MySQL. I am looking for an opportunity where I can utilize my skillset to change people’s lives.
user_title: Software Engineer
email: davidxu198556@gmail.com
twitter_username: DavydXu
github_username:  DavidXu2017
gplus_username:  guangyuxu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
